# Generated by Django 5.1.6 on 2025-02-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapitem',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=255),
        ),
    ]
